void treeviewer() {
//=========Macro generated by ROOT version5.22/00
//=========for tree "tdT" (Wed Nov 24 17:20:22 2010)
//===This macro can be opened from a TreeViewer session after loading
//===the corresponding tree, or by running root with the macro name argument

   open_session();
}

open_session(void *p = 0) {
   gSystem->Load("libTreeViewer");
   TTreeViewer *treeview = (TTreeViewer *) p;
   if (!treeview) treeview = new TTreeViewer();
   TTree *tv_tree = (TTree*)gROOT->FindObject("tdT");
   TFile *tv_file = (TFile*)gROOT->GetListOfFiles()->FindObject("outTime.root");
   if (!tv_tree) {
      if (!tv_file) tv_file = new TFile("outTime.root");
      if (tv_file)  tv_tree = (TTree*)tv_file->Get("tdT");
      if(!tv_tree) {
         printf("Tree %s not found", fTree->GetName());
         return;
      }
   }

   treeview->SetTreeName("tdT");
   treeview->SetNexpressions(10);
//         Set expressions on axis and cut
   TTVLVEntry *item;
//   X expression
   item = treeview->ExpressionItem(0);
   item->SetExpression("RSCFD_C2 - RSCFD_C3", "~Time(second)");
//   Y expression
   item = treeview->ExpressionItem(1);
   item->SetExpression("", "-empty-");
//   Z expression
   item = treeview->ExpressionItem(2);
   item->SetExpression("", "-empty-");
//   Cut expression
   item = treeview->ExpressionItem(3);
   item->SetExpression("Q_C2 > 1.2 && && Q_C3 > 0.7 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3> 5.e-9", "~RSCFD_C2 - RSCFD_C3");
//         Scan list
   item = treeview->ExpressionItem(4);
   item->SetExpression("", "Scan box");
//         User defined expressions
   item = treeview->ExpressionItem(5);
   item->SetExpression("Q_C2 > 1.2 && Q_C2 < 2.7 && Q_C3 > 0.7 && Q_C2 < 1.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 1.2- 2.7,Q_C3 0.7-1.1", kTRUE);
   item = treeview->ExpressionItem(6);
   item->SetExpression("Q_C2 > 1.2 && Q_C2 < 2.7 && Q_C3 > 1.1 && Q_C2 < 2.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 1.2- 2.7, Q_C3 1.1-2.1", kTRUE);
   item = treeview->ExpressionItem(7);
   item->SetExpression("Q_C2 > 1.2 && Q_C2 < 2.7 && Q_C3 > 2.1 && Q_C2 < 3.5 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 1.2-2.7, Q_C3 2.1-3.5", kTRUE);
   item = treeview->ExpressionItem(8);
   item->SetExpression("Q_C2 > 1.2 && Q_C2 < 2.7 && Q_C3 > 3.5 && Q_C2 < 5.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 1.2-2.7,Q _C3 3.5-5.1", kTRUE);
   item = treeview->ExpressionItem(9);
   item->SetExpression("Q_C2 > 2.7 && Q_C2 < 4.2 && Q_C3 > 0.7 && Q_C2 < 1.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 2.7-4.2,Q _C3 0.7-1.1", kTRUE);
   item = treeview->ExpressionItem(10);
   item->SetExpression("Q_C2 > 4.2 && Q_C2 < 5.7 && Q_C3 > 0.7 && Q_C2 < 1.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 4.2-5.7,Q _C3 0.7-1.1", kTRUE);
   item = treeview->ExpressionItem(11);
   item->SetExpression("Q_C2 > 5.7 && Q_C2 < 7.2 && Q_C3 > 0.7 && Q_C2 < 1.1 && RSCFD_C2-RSCFD_C3 < 15.e-9 && RSCFD_C2-RSCFD_C3 > 5.e-9", "Q_C2 5.7-7.2,Q _C3 0.7-1.1", kTRUE);
   item = treeview->ExpressionItem(12);
   item->SetExpression("Q_C3 >1.24 && Q_C3 < 2.12 && Q_C2 > 0.94 && Q_C2 < 2.28 && T2_CL-T3_CL <1 && T2_CL-T3_CL>-1", "~Q3_1~2phe_Q2_1~3phe", kTRUE);
   item = treeview->ExpressionItem(13);
   item->SetExpression("Q_C3 > 1.24 && Q_C3 < 2.12 && Q_C2 > 0.94 && Q_C2 < 2.95 && T2_CL-T3_CL < 1 && T2_CL-T3_CL>-1", "~Q3_1~2phe_Q_C2_1~4phe", kTRUE);
   item = treeview->ExpressionItem(14);
   item->SetExpression("", "-empty-", kFALSE);
//--- session object
   tv_session = new TTVSession(treeview);
   treeview->SetSession(tv_session);
//--- Connect first record
   tv_session->First();
}
